# Generated by Django 4.2.3 on 2023-08-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(default='', max_length=50)),
                ('productCode', models.IntegerField(default=0)),
                ('productName', models.CharField(max_length=150)),
                ('category', models.CharField(default='', max_length=50)),
                ('brand', models.CharField(default='', max_length=50)),
                ('unit', models.CharField(default='', max_length=20)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=7)),
                ('taxMethod', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
